//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notatnik.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notatnik.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu White.
        /// </summary>
        public static string Bialy {
            get {
                return ResourceManager.GetString("Bialy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Undo.
        /// </summary>
        public static string Cofnij {
            get {
                return ResourceManager.GetString("Cofnij", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Black.
        /// </summary>
        public static string Czarny {
            get {
                return ResourceManager.GetString("Czarny", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Red.
        /// </summary>
        public static string Czerwony {
            get {
                return ResourceManager.GetString("Czerwony", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Print.
        /// </summary>
        public static string Drukuj {
            get {
                return ResourceManager.GetString("Drukuj", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Editi.
        /// </summary>
        public static string Edycja {
            get {
                return ResourceManager.GetString("Edycja", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Text files (*.txt)|.txt|XML files (*.xml)|*.xml|Source files (*.cs)|.cs|All files (*.*)|*.*.
        /// </summary>
        public static string FiltryOkienDialogowych {
            get {
                return ResourceManager.GetString("FiltryOkienDialogowych", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Purple.
        /// </summary>
        public static string Fioletowy {
            get {
                return ResourceManager.GetString("Fioletowy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Date/Time.
        /// </summary>
        public static string GodzinaData {
            get {
                return ResourceManager.GetString("GodzinaData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Background color.
        /// </summary>
        public static string KolorTla {
            get {
                return ResourceManager.GetString("KolorTla", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Copy.
        /// </summary>
        public static string Kopiuj {
            get {
                return ResourceManager.GetString("Kopiuj", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Blue.
        /// </summary>
        public static string Niebiestki {
            get {
                return ResourceManager.GetString("Niebiestki", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New.
        /// </summary>
        public static string Nowy {
            get {
                return ResourceManager.GetString("Nowy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Recent files.
        /// </summary>
        public static string Ostatnie_pliki {
            get {
                return ResourceManager.GetString("Ostatnie pliki", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open.
        /// </summary>
        public static string Otworz {
            get {
                return ResourceManager.GetString("Otworz", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tool bar.
        /// </summary>
        public static string PasekNarzedzi {
            get {
                return ResourceManager.GetString("PasekNarzedzi", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu State bar.
        /// </summary>
        public static string PasekStanu {
            get {
                return ResourceManager.GetString("PasekStanu", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu File.
        /// </summary>
        public static string Plik {
            get {
                return ResourceManager.GetString("Plik", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Orange.
        /// </summary>
        public static string Pomaranczowy {
            get {
                return ResourceManager.GetString("Pomaranczowy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Redo.
        /// </summary>
        public static string Powtorz {
            get {
                return ResourceManager.GetString("Powtorz", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gray.
        /// </summary>
        public static string Szary {
            get {
                return ResourceManager.GetString("Szary", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Notepad.
        /// </summary>
        public static string TytulOkna {
            get {
                return ResourceManager.GetString("TytulOkna", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete.
        /// </summary>
        public static string Usun {
            get {
                return ResourceManager.GetString("Usun", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu View.
        /// </summary>
        public static string Widok {
            get {
                return ResourceManager.GetString("Widok", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Paste.
        /// </summary>
        public static string Wklej {
            get {
                return ResourceManager.GetString("Wklej", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose file to save.
        /// </summary>
        public static string WybierzPlikDoZapisu {
            get {
                return ResourceManager.GetString("WybierzPlikDoZapisu", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose text file.
        /// </summary>
        public static string WybierzPlikTekstowy {
            get {
                return ResourceManager.GetString("WybierzPlikTekstowy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cut.
        /// </summary>
        public static string Wytnij {
            get {
                return ResourceManager.GetString("Wytnij", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Exit.
        /// </summary>
        public static string Zakmnij {
            get {
                return ResourceManager.GetString("Zakmnij", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save.
        /// </summary>
        public static string Zapisz {
            get {
                return ResourceManager.GetString("Zapisz", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save as....
        /// </summary>
        public static string ZapiszJako {
            get {
                return ResourceManager.GetString("ZapiszJako", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save text file.
        /// </summary>
        public static string ZapiszPlikTekstowy {
            get {
                return ResourceManager.GetString("ZapiszPlikTekstowy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wrap lines.
        /// </summary>
        public static string ZawiajaWierze {
            get {
                return ResourceManager.GetString("ZawiajaWierze", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Slelct all.
        /// </summary>
        public static string ZaznaczWszytsko {
            get {
                return ResourceManager.GetString("ZaznaczWszytsko", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Green.
        /// </summary>
        public static string Zielony {
            get {
                return ResourceManager.GetString("Zielony", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Yellow.
        /// </summary>
        public static string Zolty {
            get {
                return ResourceManager.GetString("Zolty", resourceCulture);
            }
        }
    }
}
